# Generated by Django 5.0.6 on 2024-08-22 16:18

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='NDC Instructor', max_length=255)),
                ('specialization', models.CharField(default='Construction Softwares', max_length=255)),
                ('profile_image', models.ImageField(null=True, upload_to='instructors_profile')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Instructors',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('teacher_course_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('whocanjoin', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Course/Thumbnails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Course.instructors')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=255)),
                ('Middle_Name', models.CharField(max_length=255)),
                ('Last_Name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ('-created_at',),
            },
        ),
    ]
