# Generated by Django 5.0.6 on 2024-08-21 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bdd49150-d157-4f06-aed5-00156a61ff97'), editable=False, primary_key=True, serialize=False),
        ),
    ]
